-- Teachers table (H2 syntax)
CREATE TABLE IF NOT EXISTS teachers (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    certification_info VARCHAR(255),
    join_date DATE,
    accumulated_xp INTEGER DEFAULT 0,
    title VARCHAR(50)
    );

-- Courses table
CREATE TABLE IF NOT EXISTS courses (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       title VARCHAR(100) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    grade_level VARCHAR(50) NOT NULL,
    subject VARCHAR(100) NOT NULL,
    created_date DATE,
    xp_value INTEGER NOT NULL,
    size_category CHAR(1) NOT NULL,
    recommended_age INTEGER NOT NULL,
    teacher_id BIGINT NOT NULL,
    FOREIGN KEY (teacher_id) REFERENCES teachers(id)
    );

-- Add other tables as needed